DROP TABLE IF EXISTS IMG;
CREATE TABLE IMG (
    PHOTO_ID INTEGER NOT NULL,
    EARTH_DATE DATE NOT NULL,
    CAMERA_NAME VARCHAR(255) NOT NULL,
    IMG_SRC VARCHAR(255) NOT NULL,
    PRIMARY KEY (PHOTO_ID)
);